pipeline {
        agent {
    node {
      label 'slave1'
    }
  }
  stages {
      stage('Kubescape Report for DI'){
          steps {
              script{
                sh 'helm template -f K8s-deployment/Charts/data-ingestion/values.yaml -f K8s-deployment/Charts/data-ingestion/example-azure-resource-values.yaml K8s-deployment/Charts/data-ingestion  > di-server.yaml'
                sh 'kubescape scan -t 25 -vv di-server.yaml --format pretty-printter --output di-report'
              }
          }
          post {
                always {
               publishHTML([allowMissing: true, alwaysLinkToLastBuild:  true, keepAll: true, reportDir: '/var/lib/jenkins/workspace/kubescape-di/', reportFiles: 'di-report.txt', reportName: 'Kubescape Scan Report for DI'])

                }
            }
      }
  }
}