pipeline {
        agent {
    node {
      label 'slave1'
    }
  }
  stages {
      stage('Kubescape Report for Cat'){
          steps {
              script{
               sh 'helm template -f K8s-deployment/Charts/catalogue/values.yaml -f K8s-deployment/Charts/catalogue/example-azure-resource-values.yaml K8s-deployment/Charts/catalogue  > cat-server.yaml'
               sh 'kubescape scan -vv cat-server.yaml --format pretty-printer --output cat-report'
              }
          }
          post {
                always {
               publishHTML([allowMissing: true, alwaysLinkToLastBuild:  true, keepAll: true, reportDir: '/var/lib/jenkins/workspace/kubescape-cat/', reportFiles: 'cat-report.txt', reportName: 'Kubescape Scan Report for CAT'])
                }
            }
      }
  }
}
