{
 "title": "Basic System Metrics",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info, host)"
   }
  ]
 },
 "panels": [
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servers up ( or can pull  metrics from!)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"servers\"} ==  bool 1)"
    }
   ]
  },
  {
   "title": "Servers down ( or can't pull  metrics from!)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"servers\"} < bool  1 )"
    }
   ]
  },
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",host=~\"$node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{host=~\"$node\"}) /  count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{host=~\"$node\"}) /  count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{host=~\"$node\"} * 100) / node_memory_MemTotal_bytes{host=~\"$node\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{host=~\"$node\"} - node_memory_SwapFree_bytes{host=~\"$node\"}) / (node_memory_SwapTotal_bytes{host=~\"$node\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{host=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{host=~\"$node\"} - node_boot_time_seconds{host=~\"$node\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{host=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$node\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{host=~\"$node\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(sum by(mode) (irate(node_cpu_seconds_total{mode=\"system\",host=~\"$node\"}[5m]))) * 100  / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "avg(sum by(mode) (irate(node_cpu_seconds_total{mode=\"user\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
     "legendFormat": "Busy User"
    },
    {
     "expr": "avg( sum by(mode) (irate(node_cpu_seconds_total{mode=\"iowait\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "avg(sum by(mode) (irate(node_cpu_seconds_total{mode=~\".*irq\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "avg(sum by (mode)(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"idle\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$node\"} - node_memory_MemFree_bytes{host=~\"$node\"} - (node_memory_Cached_bytes{host=~\"$node\"} + node_memory_Buffers_bytes{host=~\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{host=~\"$node\"} + node_memory_Buffers_bytes{host=~\"$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{host=~\"$node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{host=~\"$node\"} - node_memory_SwapFree_bytes{host=~\"$node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{host=~\"$node\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{host=~\"$node\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$node\",device!~\"rootfs\"} * 100) / node_filesystem_size_bytes{host=~\"$node\",device!~\"rootfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",host=~\"$node\"}[5m]))) * 100   / count(count(node_cpu_seconds_total{instance=~\"\",job=~\"servers\"}) by (cpu))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"user\",host=~\"$node\"}[5m])))   * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "avg( sum by(mode)  (irate(node_cpu_seconds_total{mode=\"nice\",host=~\"$node\"}[5m]))) * 100  / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "avg( sum by (mode) (irate(node_cpu_seconds_total{mode=\"idle\",host=~\"$node\"}[5m])))  * 100  / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"iowait\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"irq\",host=~\"$node\"}[5m])))  * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"softirq\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "avg (sum by (mode) (irate(node_cpu_seconds_total{mode=\"steal\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"guest\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$node\"} - node_memory_MemFree_bytes{host=~\"$node\"} - node_memory_Buffers_bytes{host=~\"$node\"} - node_memory_Cached_bytes{host=~\"$node\"} - node_memory_Slab_bytes{host=~\"$node\"} - node_memory_PageTables_bytes{host=~\"$node\"} - node_memory_SwapCached_bytes{host=~\"$node\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{host=~\"$node\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{host=~\"$node\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{host=~\"$node\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{host=~\"$node\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{host=~\"$node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{host=~\"$node\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{host=~\"$node\"} - node_memory_SwapFree_bytes{host=~\"$node\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{host=~\"$node\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{host=~\"$node\"}[5m])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~\"$node\"}[5m])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{host=~\"$node\", device!~\"rootfs\"} - node_filesystem_avail_bytes{host=~\"$node\",device!~\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{host=~\"$node\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{host=~\"$node\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{host=~\"$node\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{host=~\"$node\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{host=~\"$node\",device=~\"[a-z]*[a-z]\"} [5m])",
     "legendFormat": "{{device}} - Time spent doing I/Os"
    }
   ]
  }
 ]
}