{
 "title": "immudb Performance Metrics",
 "description": "Performance metrics and statistics for immudb, a lightweight, high-speed immutable database for systems and applications.",
 "tags": [
  "immudb",
  "performance",
  "prometheus",
  "immugw"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "immudb - immudb is a lightweight, high-speed immutable database for systems and applications",
   "type": "text",
   "description": "Collected key metrics are:\n\n* no. instances\n* Current reads\n* Current writes\n* immudb functions\n* Pending operations\n* Blocked operations\n* Total numbers over time\n* Details of disk and log usage\n* immugw auditor results\n\n[immudb website](https://immudb.io/)\n\n[immudb GitHub](https://github.com/codenotary/immudb)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\n# immudb\nimmudb is a **lightweight, high-speed immutable database** for systems and applications. Written in Go.\nWith immudb you can track changes in sensitive data in your transactional databases and then record those changes permanently in a\ntamperproof immudb database. This allows you to keep an indelible history of sensitive data, for example debit/credit card transactions.\n\nTraditional transaction logs are hard to scale and are mutable. So there is no way to know for sure if your data has been compromised.\n\nAs such, immudb provides **unparalleled insights** **retroactively** of changes to your sensitive data, even\nif your perimeter has been compromised. immudb guarantees immutability by using a **Merkle tree structure** internally.\n\n## Prometheus integration\nThis dashboard uses a Prometheus datasource and expects the Prometheus job **immudbmetrics**\n\n[immudb website](https://immudb.io/)\n\n[immudb GitHub](https://github.com/codenotary/immudb)\n\n\n"
   }
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Immudb Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{pod=~\"immudb.*\"}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "immudb DBs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(immudb_number_of_stored_entries)"
    }
   ]
  },
  {
   "title": "Stored entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "immudb_number_of_stored_entries",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "immudb_pending_writes_total", "legendFormat": "{{ database }}" }
   ]
  },
  {
   "title": "Blocked",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "immudb_blocked_puts_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "immudb db sizes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immudb_db_size_bytes", "legendFormat": "{{db}}" }
   ]
  },
  {
   "title": "immudb Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Written Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(immudb_number_of_stored_entries[2m])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Write bytes/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(immudb_written_bytes[2m])",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Read bytes/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "irate(immudb_read_bytes[2m])", "legendFormat": "{{ db }}" }
   ]
  },
  {
   "title": "Started Functions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grpc_server_started_total[2m]) != 0",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Handled Functions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grpc_server_handled_total[2m]) != 0",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grpc_server_msg_received_total[2m]) != 0",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grpc_server_msg_sent_total[2m])!= 0",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Reads",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "immudb_disk_reads_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Gets",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "immudb_gets_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Writes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "immudb_disk_writes_total", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Puts",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "immudb_puts_total", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "puts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(immudb_puts_total[2m])", "legendFormat": "{{ db }}" }
   ]
  },
  {
   "title": "gets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(immudb_gets_total[2m])", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "memtable gets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_memtable_gets_total[2m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pending writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_pending_writes_total[2m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "disk reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_disk_reads_total[2m])*60",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "disk writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_disk_writes_total[2m])*60",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "bytes read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(immudb_read_bytes[2m])*60", "legendFormat": "{{ db }}" }
   ]
  },
  {
   "title": "bytes written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_written_bytes[2m])*60",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "LSM Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_lsm_size_bytes[2m])*60",
     "legendFormat": "{{ db  }}"
    }
   ]
  },
  {
   "title": "Value Log Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_vlog_size_bytes[2m])*60",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  { "title": "LSM (log-structured merge)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "bloom hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_lsm_bloom_hits_total[2m])*60",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "level gets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(immudb_lsm_level_gets_total[2m])*60",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  { "title": "immugw Auditor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Auditor Result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "immugw_audit_result_per_server", "legendFormat": "{{ db }}" }
   ]
  },
  {
   "title": "Current Root",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "immugw_audit_curr_root_per_server",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Previous Root",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "immugw_audit_prev_root_per_server",
     "legendFormat": "{{ db }}"
    }
   ]
  }
 ]
}