{
 "title": "Logstash-Elasticsarch Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Database Alerts Panel",
   "type": "graph",
   "description": "Database Alerts based on error and warn log count",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Log Count" }
   ],
   "targets": [
    {
     "expr": "count_over_time({pod=~\"logstash-logstash-.*\"} |~ `\"level\":\"ERROR\"` | regexp `({\".*)(\"error\":\")(?P<reason>.*)(\"}}.*)`[1m]) ",
     "legendFormat": "ERROR=json-parse error  REASON={{reason}}  LOC=pod  '{{pod}}' at host '{{hostname}}'"
    },
    {
     "expr": "count_over_time({pod=~\"logstash-logstash-.*\"} |~ `\"level\":\"WARN\"`| regexp `(\\{.*)({\"message\":.*)(\"error\":{\"type\":\"(mapper_parsing_exception|strict_dynamic_mapping_exception|index_not_found_exception|\\w+)\",\"reason\":\")(?P<reason>.*)(\"}}.*)`[1m])",
     "legendFormat": "ERROR='{{error_type}}' for index '{{index}}'  REASON={{reason}}  LOC=pod '{{pod}}' at host '{{hostname}}' "
    },
    {
     "expr": "count_over_time({pod=~\"elasticsearch-.*\"} |~ `\"level\": \"ERROR\"`| regexp `(\\{.*)(\"level\": \")(?P<level>\\w+)(.*)(\"component\": \")(?P<component>[^\"]+)(\",\\s+)(\"cluster\\.name\": \")(?P<cluster_name>[^\"]+)(\",\\s+)(\"node\\.name\": \")(?P<node_name>[^\"]+)(\",\\s+)(\"message\": \")(?P<message>.*)(\",\\s+)(\"cluster\\.uuid\": \".*)` [1m]) ",
     "legendFormat": "ERROR=es error at {{component}}  REASON={{message}}  LOC=pod '{{pod}}' at host '{{hostname}}' "
    }
   ]
  },
  { "title": "Alert Notifications", "type": "alertlist", "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 } },
  { "title": "Elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Elasticsearch logs ",
   "type": "logs",
   "description": "Displays warn and error logs of elasticsearch",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{pod=~\"elasticsearch-.*\"} | regexp `(\\{.*)(\"level\": \")(?P<level>\\w+)(.*)(\"component\": \")(?P<component>[^\"]+)(\",\\s+)(\"cluster\\.name\": \")(?P<cluster_name>[^\"]+)(\",\\s+)(\"node\\.name\": \")(?P<node_name>[^\"]+)(\",\\s+)(\"message\": \")(?P<message>.*)(\",\\s+)(\"cluster\\.uuid\": \".*)`  | line_format \"LOCATION={{.container_name}} in {{.host}} node  CLUSTER={{.cluster_name}}  NODE={{.node_name}}  LEVEL={{ToLower .level}}  COMPONENT={{.component}}\\nMESSAGE=\\\"{{.message}}\\\"\""
    }
   ]
  },
  { "title": "Logstash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Logstash logs ",
   "type": "logs",
   "description": "Displays warn and error logs of logstash",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{pod=~\"logstash-logstash-.*\"} "
    }
   ]
  }
 ]
}