{
 "title": "Node Level Metrics",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers up ( or can pull  metrics from!)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"servers\"} ==  bool 1)"
    }
   ]
  },
  {
   "title": "Servers down ( or can't pull  metrics from!)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"servers\"} < bool  1 )"
    }
   ]
  },
  {
   "title": "Node up/down status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"servers\"}"
    }
   ]
  },
  {
   "title": "$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{host=~\"$node\"}) /  count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{host=~\"$node\"} * 100) / node_memory_MemTotal_bytes{host=~\"$node\"})"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{host=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{host=~\"$node\"} - node_boot_time_seconds{host=~\"$node\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{host=~\"$node\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{host=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 5, "w": 3, "x": 19, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(mode) (irate(node_cpu_seconds_total{mode=\"system\",host=~\"$node\"}[5m]))) * 100  / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "avg(sum by(mode) (irate(node_cpu_seconds_total{mode=\"user\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
       "legendFormat": "Busy User"
      },
      {
       "expr": "avg( sum by(mode) (irate(node_cpu_seconds_total{mode=\"iowait\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "avg(sum by(mode) (irate(node_cpu_seconds_total{mode=~\".*irq\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "avg(sum by (mode)(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu)) ",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "avg(sum by (mode) (irate(node_cpu_seconds_total{mode=\"idle\",host=~\"$node\"}[5m]))) * 100 / count(count(node_cpu_seconds_total{host=~\"$node\"}) by (cpu))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$node\",device!~\"rootfs\"} * 100) / node_filesystem_size_bytes{host=~\"$node\",device!~\"rootfs\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{host=~\"$node\"}[5m])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{host=~\"$node\"}[5m])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{host=~\"$node\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{host=~\"$node\"} - node_memory_MemFree_bytes{host=~\"$node\"} - (node_memory_Cached_bytes{host=~\"$node\"} + node_memory_Buffers_bytes{host=~\"$node\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{host=~\"$node\"} + node_memory_Buffers_bytes{host=~\"$node\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{host=~\"$node\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{host=~\"$node\"} - node_memory_SwapFree_bytes{host=~\"$node\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    }
   ]
  }
 ]
}