{
 "title": "Analytics Components Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ClickHouse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clickhouse Server 3",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-server-3.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Server 2",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-server-2.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Server 4",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-server-4.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Server 1",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-server-1.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Keeper 3",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-keeper-3.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Keeper 2",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-keeper-2.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Keeper 1",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_clickhouse-keeper-1.1.*\"}"
      }
     ]
    },
    {
     "title": "Clickhouse Chproxy",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "{container_name=~\"clickhouse-cluster_chproxy.1.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Superset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Superset Dashboard",
     "type": "logs",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{container_name=~\"superset_superset.1.*\"}"
      }
     ]
    },
    {
     "title": "Superset worker beat",
     "type": "logs",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "{container_name=~\"superset_superset-worker-beat.*\"}"
      }
     ]
    },
    {
     "title": "Superset worker",
     "type": "logs",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 13 },
     "targets": [
      {
       "expr": "{container_name=~\"superset_superset-worker.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flink Jobmanager Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{container_name=~\"flink_jobmanager.*\"}"
      }
     ]
    },
    {
     "title": "Flink TaskManager Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "{container_name=~\"flink_taskmanager.*\"}"
      }
     ]
    }
   ]
  },
  { "title": "Minio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Minio Cluster Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container_name=~\"minio_minio[1-4].*\"}"
    }
   ]
  }
 ]
}