{
 "title": "Vertx Apps Metrics and Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Application", "query": { "query": "label_values(namespace)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{namespace=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs ",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Quick facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "No. of  Instances up in cluster : $cluster ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(up{namespace=\"$cluster\"})"
      },
      {}
     ]
    },
    {
     "title": "Process Current  CPU Usage : $instance",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_usage{pod=\"$instance\"} ",
       "legendFormat": " ",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-Heap used : $instance  ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{pod=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": " Heap used :  $instance ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{pod=\"$instance\", area=\"heap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory per instance : $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": " JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 2, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": " JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": " JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc per instance : $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": " CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{pod=\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{pod=\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{pod=\"$instance\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{pod=\"$instance\"}",
       "legendFormat": "cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{pod=\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{pod=\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{pod=\"$instance\"}",
       "legendFormat": "peak"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{pod=\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Metrics per instance:  $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertx_http_server_active_connections{namespace=\"$cluster\",pod=\"$instance\"}) ",
       "legendFormat": "Active connections"
      }
     ]
    },
    {
     "title": "Response time by code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vertx_http_server_response_time_seconds_sum{namespace=\"$cluster\", pod=\"$instance\"}[2m])) by (code) / sum(irate(vertx_http_server_response_time_seconds_count{namespace=\"$cluster\", pod=\"$instance\"}[2m])) by (code)",
       "legendFormat": "{{code}} 1 m instant"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le,path))",
       "legendFormat": "{{code}} [med]"
      }
     ]
    },
    {
     "title": "Request count rate by code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(rate(vertx_http_server_requests_total{namespace=\"$cluster\",pod=\"$instance\"}[2m])) by (code), 0.001)"
      }
     ]
    },
    {
     "title": "Response time/latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vertx_http_server_response_time_seconds_sum{namespace=\"$cluster\", pod=\"$instance\"}[2m])) / sum(irate(vertx_http_server_response_time_seconds_count{namespace=\"$cluster\", pod=\"$instance\"}[2m])) ",
       "legendFormat": "2 minute  instant latency"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "[med]"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "[95p]"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "[99p]"
      },
      {
       "expr": "sum(rate(vertx_http_server_response_time_seconds_sum{namespace=\"$cluster\", pod=\"$instance\"}[2m]))  / sum(rate(vertx_http_server_response_time_seconds_count{namespace=\"$cluster\", pod=\"$instance\"}[2m])) ",
       "legendFormat": "2 minute avg latency "
      }
     ]
    },
    {
     "title": "Throughput ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_http_server_response_time_seconds_count{namespace=\"$cluster\", pod=\"$instance\",code=\"200\"}[2m])) /sum(rate(vertx_http_server_response_time_seconds_sum{namespace=\"$cluster\",pod=\"$instance\",code=\"200\"} [2m])) ",
       "legendFormat": "{{code}} 2 miniute avg "
      },
      {
       "expr": "sum(irate(vertx_http_server_response_time_seconds_count{namespace=\"$cluster\", pod=\"$instance\", code=\"200\"}[1m]))  by (code) /sum(irate(vertx_http_server_response_time_seconds_sum{namespace=\"$cluster\", pod=\"$instance\",code=\"200\"} [1m])) by (code) ",
       "legendFormat": "{{code}} 2 minute instant "
      }
     ]
    },
    {
     "title": "Total HTTP Server bytes sent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_http_server_response_bytes_sum{namespace=\"$cluster\",pod=\"$instance\"}[2m])) / sum(rate(vertx_http_server_response_bytes_count{namespace=\"$cluster\",pod=\"$instance\"}[2m]))",
       "legendFormat": "[avg]"
      }
     ]
    },
    {
     "title": "Total  HTTP Server bytes received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_http_server_request_bytes_sum{namespace=\"$cluster\",pod=\"$instance\"}[2m])) / sum(rate(vertx_http_server_request_bytes_count{namespace=\"$cluster\",pod=\"$instance\"}[2m]))",
       "legendFormat": "[avg]"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Event Bus Metrics per instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eventbus: handlers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertx_eventbus_handlers{namespace=\"$cluster\", pod=\"$instance\"}) by (address)",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Eventbus: pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertx_eventbus_pending{namespace=\"$cluster\", pod=\"$instance\"}) by (address)",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Eventbus: total sent rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vertx_eventbus_sent_total{namespace=\"$cluster\", pod=\"$instance\"}[2m]))",
       "legendFormat": "2 minute instant rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_sent_total{cluster=\"$cluster\", instance=\"$instance\"}[2m]))",
       "legendFormat": "2 minute rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_sent_total{cluster=\"$cluster\", instance=\"$instance\"}[5m])) ",
       "legendFormat": "5 minute rate"
      },
      {}
     ]
    },
    {
     "title": "Eventbus: total received rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vertx_eventbus_received_total{namespace=\"$cluster\", pod=\"$instance\"}[2m]))",
       "legendFormat": "2 minute instant rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_received_total{cluster=\"$cluster\", instance=\"$instance\"}[2m]))",
       "legendFormat": "2 minute  avg rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_received_total{cluster=\"$cluster\", instance=\"$instance\"}[5m]))",
       "legendFormat": "5 minute avg rate"
      },
      {}
     ]
    },
    {
     "title": "Eventbus : processing  rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_eventbus_processed_total{namespace=\"$cluster\",pod=\"$instance\"}[2m]))",
       "legendFormat": "[avg]"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "[med]"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "[95p]"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{cluster=\"$cluster\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "[99p]"
      }
     ]
    },
    {
     "title": "Eventbus: processing rate by address",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_eventbus_processed_total{namespace=\"$cluster\",pod=\"$instance\"}[2m])) by (address)",
       "legendFormat": "{{address}} [avg]"
      }
     ]
    }
   ]
  }
 ]
}