{
 "title": "Vertx Applications alerts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Alert Notifications", "type": "alertlist", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 } },
  { "title": "AAA server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "AAA Server Alerts Panel",
   "type": "graph",
   "description": "AAA server Alerts based on error  log count",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Log Count" }
   ],
   "targets": [
    {
     "expr": "count_over_time({pod=~\"aaa-.*\"} |~ \"ERROR\" | regexp `(.*)(loggerName=)(?P<loggerName>.*)(message=)(?P<reason>.*)(source=.*)`[1m])",
     "legendFormat": " ERROR in  auth  server  LOGGERNAME={{loggerName}} REASON={{reason}}  LOC=pod  '{{pod}}' at host '{{hostname}}'"
    }
   ]
  },
  {
   "title": "AAA Server  logs ",
   "type": "logs",
   "description": "Displays  logs of AAA  server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{pod=~\"aaa-.*\"}"
    }
   ]
  },
  { "title": "Catalogue Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Catalogue Server Alerts Panel",
   "type": "graph",
   "description": "Catalogue server Alerts based on error  log count",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Log Count" }
   ],
   "targets": [
    {
     "expr": "count_over_time({pod=~\"cat-.*\"} |~ \"ERROR\" | regexp `(.*)(loggerName=)(?P<loggerName>.*)(message=)(?P<reason>.*)(source=.*)`[1m])",
     "legendFormat": " ERROR in  catalogue server  LOGGERNAME={{loggerName}} REASON={{reason}}  LOC=pod  '{{pod}}' at host '{{hostname}}'"
    }
   ]
  },
  {
   "title": "Catalogue Server  logs ",
   "type": "logs",
   "description": "Displays  logs of Catalogue server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{pod=~\"cat-.*\"}"
    }
   ]
  },
  { "title": "Resource Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Resource Server Alerts Panel",
   "type": "graph",
   "description": "Resource server Alerts based on error  log count",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Log Count" }
   ],
   "targets": [
    {
     "expr": "count_over_time({pod=~\"rs-.*\"} |~ \"ERROR|\" !~ `\"failed to decode/validate jwt token.*\"|\"Error : Authentication Failure.*\"|\"error : failed.*\"|\"Fail: Search Fail\"`| regexp `(.*)(loggerName=)(?P<loggerName>.*)(message=)(?P<reason>.*)(source=.*)`[1m])",
     "legendFormat": " ERROR in  resource server  LOGGERNAME={{loggerName}} REASON={{reason}}  LOC=pod  '{{pod}}' at host '{{hostname}}'"
    }
   ]
  },
  {
   "title": "Resource Server  logs ",
   "type": "logs",
   "description": "Displays  logs of resource server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{pod=~\"rs-.*\"}"
    }
   ]
  },
  { "title": "File server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "File Server Alerts Panel",
   "type": "graph",
   "description": "File server Alerts based on error  log count",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Log Count" }
   ],
   "targets": [
    {
     "expr": "count_over_time({pod=~\"fs-.*\"}|~\"ERROR\"!~\"File does not exist.*\"| regexp `(.*)(loggerName=)(?P<loggerName>.*)(message=)(?P<reason>.*)(source=.*)`[1m])",
     "legendFormat": " ERROR in  file server  LOGGERNAME={{loggerName}} REASON={{reason}}  LOC=pod  '{{pod}}' at host '{{hostname}}'"
    }
   ]
  },
  {
   "title": "File  Server  logs ",
   "type": "logs",
   "description": "Displays  logs of File server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "{pod=~\"fs-.*\"}"
    }
   ]
  },
  { "title": "Latest ingestion pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Latest Ingestion Alerts Panel",
   "type": "graph",
   "description": "Latest Ingestion Alerts based on error  log count",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "Log Count" }
   ],
   "targets": [
    {
     "expr": "count_over_time({pod=~\"lip-.*\"} |~ \"ERROR\" | regexp `(.*)(loggerName=)(?P<loggerName>.*)(message=)(?P<reason>.*)(source=.*)`[1m])",
     "legendFormat": " ERROR in latest ingestion  REASON={{reason}}  LOC=pod  '{{pod}}' at host '{{hostname}}'"
    }
   ]
  },
  {
   "title": " Latest pipeline logs ",
   "type": "logs",
   "description": "Displays  logs of latest ingestion pipeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "{pod=~\"lip-.*\"}"
    }
   ]
  }
 ]
}