{
 "title": "Summary - Critical Components",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   },
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Container Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(time() - container_last_seen{image!=\"\"} < 60)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) * 100)/ sum(machine_cpu_cores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container_name=~\"$container\"}"
    }
   ]
  },
  { "title": "Servers Up/Down status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Servers Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"servers\"} ==  bool 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers Down",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"servers\"} < bool  1 )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Black Box Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "probe_success{job=~\"blackbox\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"blackbox\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"blackbox\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"blackbox\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"blackbox\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"blackbox\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"blackbox\"}[1m])"
    }
   ]
  },
  {
   "title": "Minio Overivew",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "time() - max(minio_node_process_starttime_seconds{job=~\"minio-job\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total S3 Ingress",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"minio-job\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"minio-job\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"minio-job\"}) by (instance))",
       "legendFormat": "Used"
      },
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"minio-job\"}) by (instance)) ",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Data Usage Growth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(minio_cluster_usage_total_bytes{job=~\"minio-job\"})",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Cluster Health Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_health_status{job=~\"minio-job\"}",
       "legendFormat": "Pool: {{pool}} Set: {{set}}"
      }
     ]
    },
    {
     "title": "Number of Buckets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(minio_cluster_bucket_total{job=~\"minio-job\"})"
      }
     ]
    },
    {
     "title": "Time Since Last Scan",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(minio_usage_last_activity_nano_seconds{job=~\"minio-job\"})"
      }
     ]
    },
    {
     "title": "Total Online/Offline Drives",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(minio_cluster_drive_online_total{job=~\"minio-job\"})",
       "legendFormat": "."
      },
      {
       "expr": "max(minio_cluster_drive_offline_total{job=~\"minio-job\"})",
       "legendFormat": "."
      }
     ]
    },
    {
     "title": "Number of Objects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(minio_cluster_usage_object_total{job=~\"minio-job\"})"
      }
     ]
    },
    {
     "title": "Time Since Last Heal",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(minio_heal_time_last_activity_nano_seconds{job=~\"minio-job\"})"
      }
     ]
    },
    {
     "title": "Memory Usage ",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_node_process_resident_memory_bytes{job=~\"minio-job\"}",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  }
 ]
}