{
 "title": "CoreDNS",
 "tags": [ "coredns-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(coredns_build_info, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{kubernetes_io_name=\"CoreDNS\"})"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(coredns_panics_total)" }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{pod=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "sum(rate(coredns_forward_responses_total{pod=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "forward {{rcode}}"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{pod=~\"$instance\"}[5m])) by (server, zone, le))",
     "legendFormat": "{{server}} {{zone}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{pod=~\"$instance\"}[5m])) by (to, le))",
     "legendFormat": "forward {{to}}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Forward Requests (by to)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{pod=~\"$instance\"}[5m])) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_hits_total{pod=~\"$instance\"}) / (sum(coredns_cache_misses_total{pod=~\"$instance\"}) + sum(coredns_cache_hits_total{pod=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Cache hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{pod=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{job=\"kube-dns\",pod=~\"$instance\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{pod=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Plugins Enabled",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count(sum(coredns_plugin_enabled{pod=~\"$instance\"}) by (name))"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "99th {{server}} {{zone}} {{proto}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"kube-dns\",pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "50th {{server}} {{zone}} {{proto}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "99th {{server}} {{zone}} {{proto}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"kube-dns\",pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "50th {{server}} {{zone}} {{proto}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_io_name=\"CoreDNS\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{kubernetes_io_name=\"CoreDNS\",pod=~\"$instance\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_io_name=\"CoreDNS\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}