{
 "title": "K8S - ETCD Cluster Health",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "tags": [
  "k8s",
  "prometheus",
  "platform"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "etcd_main_volume_b", "label": "etcd_main_volume_b", "query": "vol-05a8c3a600a3cd50e" },
   { "name": "etcd_main_volume_d", "label": "etcd_main_volume_d", "query": "vol-09373a5d0d5a4ddf5" },
   { "name": "etcd_main_volume_e", "label": "etcd_main_volume_e", "query": "vol-077b59d16585c5cbd" }
  ]
 },
 "panels": [
  { "title": "ETCD Cluster View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_debugging_mvcc_db_total_size_in_bytes) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(etcd_debugging_mvcc_db_total_size_in_bytes) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "ETCD rps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",container_name=\"etcd-manager\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "RPS Successful Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",container_name=\"etcd-manager\"}[2m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "RPS Successful Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",container_name=\"etcd-manager\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Members State",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "targets": [
    { "expr": "etcd_server_is_leader" }
   ]
  },
  {
   "title": "RPS Failed Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_code!=\"OK\",container_name=\"etcd-manager\"}[5m])) by (pod_name, grpc_code)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "RPS Failed Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_code!=\"OK\",container_name=~\"etcd-manager\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{pod_name=~\"etcd-manager-main-.*\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "RPS Failed Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{grpc_code!=\"OK\",container_name=~\"etcd-manager\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Sync Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (pod_name, le))",
       "legendFormat": "{{pod_name}} WAL fsync"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (pod_name, le))",
       "legendFormat": "{{pod_name}} DB fsync"
      }
     ]
    },
    {
     "title": "Dysk Compact Duration",
     "type": "graph",
     "description": "etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count[1m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Dysk Compact Duration",
     "type": "graph",
     "description": "etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count[1m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Main EBS - Available Burst Balance",
     "type": "graph",
     "description": "If get closes to 0, maybe etcd disks will stop working smoothly",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "etcd-b",
       "dimensions": { "VolumeId": "$etcd_main_volume_b" },
       "metricName": "BurstBalance",
       "namespace": "AWS/EBS",
       "period": "5m",
       "region": "us-east-1",
       "statistics": [ "Average" ]
      },
      {
       "alias": "etcd-d",
       "dimensions": { "VolumeId": "$etcd_main_volume_d" },
       "metricName": "BurstBalance",
       "namespace": "AWS/EBS",
       "period": "5m",
       "region": "us-east-1",
       "statistics": [ "Average" ]
      },
      {
       "alias": "etcd-e",
       "dimensions": { "VolumeId": "$etcd_main_volume_e" },
       "metricName": "BurstBalance",
       "namespace": "AWS/EBS",
       "period": "5m",
       "region": "us-east-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{job=\"etcd-manager\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Heartbeat Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(etcd_server_heartbeat_send_failures_total[1m])",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Raft Proposals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
       "legendFormat": "Proposal Failure Rate"
      },
      {
       "expr": "sum(etcd_server_proposals_pending)",
       "legendFormat": "Proposal Pending Total"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
       "legendFormat": "Proposal Commit Rate"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
       "legendFormat": "Proposal Apply Rate"
      }
     ]
    },
    {
     "title": "Proposals pending",
     "type": "graph",
     "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(etcd_server_proposals_pending)",
       "legendFormat": "Proposals pending"
      }
     ]
    },
    {
     "title": "The total number of consensus proposals committed",
     "type": "graph",
     "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
       "legendFormat": "total number of consensus proposals committed"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
       "legendFormat": "total number of consensus proposals applied"
      }
     ]
    },
    {
     "title": "Client Traffic In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
       "legendFormat": "{{instance}} Client Traffic In"
      }
     ]
    },
    {
     "title": "Client Traffic Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
       "legendFormat": "{{instance}} Client Traffic Out"
      }
     ]
    },
    {
     "title": "Total Leader Elections Per Day",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
       "legendFormat": "{{instance}} Total Leader Elections Per Day"
      }
     ]
    },
    {
     "title": "Peer Traffic In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}} Peer Traffic In"
      }
     ]
    },
    {
     "title": "Peer Traffic Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 54 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}} Peer Traffic Out"
      }
     ]
    },
    {
     "title": "Disks operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum[1m]))",
       "legendFormat": "\tThe latency distributions of fsync called by wal"
      },
      {
       "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum[1m]))",
       "legendFormat": "The latency distributions of commit called by backend"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total[1m]))",
       "legendFormat": "The total number of bytes received by grpc clients"
      },
      {
       "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total[1m]))",
       "legendFormat": "The total number of bytes sent to grpc clients"
      }
     ]
    },
    {
     "title": "Snapshot duration",
     "type": "graph",
     "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum[1m]))",
       "legendFormat": "The total latency distributions of save called by snapshot"
      }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "ETCD disk io latency alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "lert if 99th percentile of round trips take 150ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[5m]))",
     "legendFormat": "{{pod_name}} to {{To}}"
    }
   ]
  },
  {
   "title": "ETCD Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"etcd-manager\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {}
   ]
  },
  {
   "title": "ETCD Leader Changes Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(etcd_server_leader_changes_seen_total[1h])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Dysk Compact Duration",
   "type": "graph",
   "description": "etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (pod_name, le))",
     "legendFormat": "{{pod_name}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (pod_name, le))",
     "legendFormat": "{{pod_name}} DB fsync"
    }
   ]
  }
 ]
}