{
 "title": "Kubernetes resource usage per namespace and pod",
 "tags": [
  "k8s",
  "resources",
  "parm_namespace",
  "view_pod"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "top", "query": "5,10,20,100" },
   {
    "name": "namespace",
    "query": {
     "query": "kube_pod_container_status_running"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "kube_pod_container_status_running"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "kube_pod_container_status_running"
    }
   },
   {
    "name": "_interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Containers CPU and MEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Sustained CPU usage  for ns=\"$namespace\" (pod=\"$pod\",container=\"$container\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top,\r\n  sum by (pod) (\r\n    max_over_time(\r\n      rate(container_cpu_usage_seconds_total{\r\n        namespace=~\"$namespace\",\r\n        pod=~\"$pod.*\",\r\n        container!=\"\"\r\n      }[1m:])[$__range:]\r\n    )\r\n  )\r\n)",
     "legendFormat": "{{cluster}} - {{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Container Burst CPU usage  for ns=\"$namespace\" (pod=\"$pod\",container=\"$container\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top,\r\n  sum by (pod) (\r\n    max_over_time(\r\n      rate(container_cpu_usage_seconds_total{\r\n        namespace=~\"$namespace\",\r\n        container!~\"POD\"\r\n      }[2m])[$__range:]\r\n    )\r\n  )\r\n)",
     "legendFormat": "{{cluster}} - {{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Container CPU Throttle  for ns=\"$namespace\" (pod=\"$pod\",container=\"$container\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod.*\",\r\n  container!=\"\",\r\n  image!=\"\"\r\n}[2m])",
     "legendFormat": "{{cluster}} - {{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "top$top container MEM usage  for ns=\"$namespace\" (pod=\"$pod\",container=\"$container\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(\n  sum by (pod) (\n    container_memory_usage_bytes{\n      namespace=~\"$namespace\",\n      pod=~\"$pod.*\",\n      container!=\"\"\n    }\n  )[${__range}:])\n)",
     "legendFormat": "{{cluster}} - {{pod}}/{{container}}"
    },
    {
     "expr": "topk($top, container_memory_working_set_bytes{namespace=~\"$namespace\",pod_name=~\"$pod.*\",container_name=~\"$container\"})",
     "legendFormat": "{{cluster}} - {{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Containers I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "top$top container IO +R -W for ns=\"$namespace\" (pod=\"$pod\",container=\"$container\") [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\",container=~\"$container\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod}}/{{container}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\",container=~\"$container\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod}}/{{container}}"
    },
    {
     "expr": "topk($top, sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\",container_name=~\"$container\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod_name}}/{{container_name}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\",container_name=~\"$container\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "top$top container IO +R -W ns=\"$namespace\" (pod=\"$pod\",container=\"$container\") [iops]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_fs_reads_total{namespace=~\"$namespace\",pod=~\"$pod.*\",container=~\"$container\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod}}/{{container}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_fs_writes_total{namespace=~\"$namespace\",pod=~\"$pod.*\",container=~\"$container\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod}}/{{container}}"
    },
    {
     "expr": "topk($top, sum(rate(container_fs_reads_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\",container_name=~\"$container\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod_name}}/{{container_name}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_fs_writes_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\",container_name=~\"$container\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Pods Network traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "top$top Pod Network +RX -TX ns=\"$namespace\" (pod=\"$pod\") [Bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod}}"
    },
    {
     "expr": "topk($top, sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod_name}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "top$top Pod Network +RX -TX ns=\"$namespace\" (pod=\"$pod\") [pkts/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum(rate(container_network_receive_packets_total{namespace=~\"$namespace\",pod=~\"$pod.*\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace\",pod=~\"$pod.*\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod}}"
    },
    {
     "expr": "topk($top, sum(rate(container_network_receive_packets_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\"}[$_interval])) without (cpu)) > 0",
     "legendFormat": "{{cluster}} - {{pod_name}}"
    },
    {
     "expr": "- topk($top, sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace\",pod_name=~\"$pod.*\"}[$_interval])) without (cpu)) < 0",
     "legendFormat": "{{cluster}} - {{pod_name}}"
    }
   ]
  }
 ]
}