pipeline {
        agent {
    node {
      label 'slave1'
    }
  }
  stages {
      stage('Kubescape Report for LIP'){
          steps {
              script{
                sh 'helm template -f K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml -f K8s-deployment/Charts/latest-ingestion-pipeline/example-azure-resource-values.yaml K8s-deployment/Charts/latest-ingestion-pipeline  > lip-server.yaml'
                sh 'kubescape scan -vv lip-server.yaml --format pretty-printer --output lip-report'
               publishHTML([allowMissing: true, alwaysLinkToLastBuild:  true, keepAll: true, reportDir: '/var/lib/jenkins/workspace/kubescape-lip/', reportFiles: 'lip-report.txt', reportName: 'Kubescape Scan Report for LIP'])
              }
          }
      }
  }
}
