{
 "title": "Server certificates and status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Certificate and connection monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Production Certificate & Connection Monitoring ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*|https://iudx.org.in/\"}-time()"
    },
    {
     "expr": "probe_http_status_code{instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"resolve\",instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\",instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"tls\",instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"processing\",instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"transfer\",instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    }
   ]
  },
  {
   "title": "Test Certificate & Connection Monitoring",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}-time()"
    },
    {
     "expr": "probe_http_status_code{instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"resolve\",instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\",instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"tls\",instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"processing\",instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"transfer\",instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"}"
    }
   ]
  },
  {
   "title": "Alerts on server certificates and status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Production Server status Alert",
   "type": "graph",
   "description": "Any production server if responded with non success status i.e. not 200,  alert is sent",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*|https://iudx.org.in/\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Production servers Cert Expiry Alert",
   "type": "graph",
   "description": "Production servers Certificates Expiry Alert, alert will be sent 2 weeks before",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " probe_ssl_earliest_cert_expiry{instance=~\"https://[A-Za-z0-9.]+.iudx.org.in[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*|https://iudx.org.in/\"} - time() ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Test servers Cert Expiry Alert",
   "type": "graph",
   "description": "Test servers Certificates Expiry Alert, alert will be sent 2 weeks before",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " probe_ssl_earliest_cert_expiry{instance=~\"https://[A-Za-z0-9.]+.iudx.io[:0-9]*/[A-Za-z0-9.\\\\-\\\\/]*\"} - time() ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}