{
 "title": "Flink",
 "description": "flink with prometheus",
 "tags": [ "flink" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job_name", "label": "job_name", "query": "label_values(job_name)" },
   {
    "name": "query0",
    "label": "scrape_jobs",
    "query": {
     "query": "label_values({scrape_job=\"flink-jm\"},scrape_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Slots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# of TaskManagers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "{{instance}} jobmanager运行的job数量"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  {
   "title": "BackPressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "inPoolUsag",
   "type": "graph",
   "description": "inPoolUsag",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inPoolUsage{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inPoolUse"
    }
   ]
  },
  {
   "title": "outPoolUsage",
   "type": "graph",
   "description": "outPoolUsage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outPoolUsage{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outPoolUsage"
    }
   ]
  },
  {
   "title": "outputQueueLength",
   "type": "graph",
   "description": "outputQueueLength",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outputQueueLength{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outputQueueLength"
    }
   ]
  },
  {
   "title": "numRecordsOutPerSecond",
   "type": "graph",
   "description": "numRecordsOutPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsOutPerSecond"
    }
   ]
  },
  {
   "title": "numRecordsInPerSecond",
   "type": "graph",
   "description": "umRecordsInPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsInPerSecond"
    }
   ]
  },
  {
   "title": "inputQueueLength",
   "type": "graph",
   "description": "inputQueueLength",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inputQueueLength{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inputQueueLength"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TaskManager Garbage Collection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc count"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc count"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc时间"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc时间"
    }
   ]
  },
  {
   "title": "live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} jobManager live Thread counts"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} taskManger live Thread counts"
    }
   ]
  },
  {
   "title": "CheckPoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "lastCheckpointDuration",
   "type": "graph",
   "description": "lastCheckpointDuration",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "Last CheckPoint Size",
   "type": "graph",
   "description": "Last CheckPoint Size",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "numberOfFailedCheckpoints",
   "type": "graph",
   "description": "numberOfFailedCheckpoints",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}_FailedCheckpoints"
    }
   ]
  },
  {
   "title": "connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "offset commit failures to Kafka",
   "type": "graph",
   "description": "offset commit failures to Kafka",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_commitsFailed{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "records has dropped due to arriving late.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numLateRecordsDropped{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "job-downtime",
   "type": "graph",
   "description": "job-downtime",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_downtime{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_downtime"
    }
   ]
  },
  {
   "title": "rocksdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "delayed write rate",
   "type": "graph",
   "description": "delayed write rate",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_actual_delayed_write_rate{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": " entries in the unflushed immutable memtables",
   "type": "graph",
   "description": "entries in the unflushed immutable memtables.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_deletes_imm_mem_tables{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}} delete entries"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_entries_imm_mem_tables{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}} total entries"
    }
   ]
  },
  {
   "title": "background errors in RocksDB",
   "type": "graph",
   "description": "background errors in RocksDB",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_background_errors{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "unreleased snapshots",
   "type": "graph",
   "description": "unreleased snapshots",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_snapshots{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JobManager Memory Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max-flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager Memory Available",
   "type": "graph",
   "description": "TaskManager Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max-flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "JobManager NonHeap Memory Available",
   "type": "graph",
   "description": "JobManager NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed-flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManger NonHeap Memory Available",
   "type": "graph",
   "description": "TaskManger NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed-flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jobmanager network  Rate per second",
   "type": "graph",
   "description": "jobmanager network Rate per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_Network_bond0_ReceiveRate",
     "legendFormat": "{{host}} ReceiveRate"
    },
    {
     "expr": "flink_jobmanager_System_Network_bond0_SendRate",
     "legendFormat": "{{host}} SendRate"
    }
   ]
  },
  {
   "title": "TaskManager network Rate per second",
   "type": "graph",
   "description": "TaskManager network Rate per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_Network_bond0_ReceiveRate",
     "legendFormat": "{{host}}_{{tm_id}} ReceiveRate"
    },
    {
     "expr": "flink_taskmanager_System_Network_bond0_SendRate",
     "legendFormat": "{{host}}_{{tm_id}} SendRate"
    }
   ]
  },
  {
   "title": "TaskManager CPU USE",
   "type": "graph",
   "description": "TaskManager CPU USE",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_CPU_Usage",
     "legendFormat": "{{host}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "JobManager CPU USE",
   "type": "graph",
   "description": "JobManager CPU USE",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_CPU_Usage",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}